spring.application.name=AIRBNBCLONE

#DB Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/AIRBNIBCLONE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.username=postgres
spring.datasource.password=password

jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdf89aabsdf876
